Update user profile branch
ChideraBel/FOBWebAPILambda pull request #17
Opened 2024-03-02 22:40 UTC by Oluwalana

updating the user profile.

2024-03-04 18:50 UTC, ChideraBel requested changes
Make those changes and update the PR.

2024-03-04 18:50 UTC, ChideraBel commented on src/main/java/org/tranqwave/fobwebapilambda/user/UpdateUserProfileLambda.java
> +            return new ResponseMessage(ERROR, String.format(" User profile with email %s does not exist", userId));
Remove unnecessary spacing before "User" and add a period at the end of response message.

2024-03-04 18:50 UTC, ChideraBel commented on src/main/java/org/tranqwave/fobwebapilambda/user/UpdateUserProfileLambda.java
> +
Remove redundant spacing.

2024-03-04 18:50 UTC, ChideraBel commented on src/main/java/org/tranqwave/fobwebapilambda/user/UpdateUserProfileLambda.java
> +        return new ResponseMessage(SUCCESS, String.format("User profile with email %s has been updated",userId));
Add period at the end of sentences returned to the UI.

2024-03-04 20:56 UTC, Oluwalana commented on src/main/java/org/tranqwave/fobwebapilambda/section/GetSectionLambda.java
what does the red in here mean again?

2024-03-04 20:58 UTC, ChideraBel commented on src/main/java/org/tranqwave/fobwebapilambda/section/GetSectionLambda.java
The Merging is Blocked ? It means that there are requested changes that you have to make and have approved. So that you're allowed to merge.

2024-03-07 22:26 UTC, ChideraBel approved these changes
👍

2024-03-07 22:34 UTC, merged